# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:09:01+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Query, UploadFile

from models import (
    FeedType,
    V3FeedsPostResponse,
    V3FulfillmentInventoryGetResponse,
    V3InventoriesGetResponse,
    V3InventoriesSkuGetResponse,
    V3InventoriesSkuPutRequest,
    V3InventoriesSkuPutResponse,
    V3InventoryGetResponse,
    V3InventoryPutRequest,
    V3InventoryPutResponse,
)

app = MCPProxy(
    contact={'x-twitter': 'Walmart'},
    description='Maintaining up-to-date inventory for your items on Walmart.com ensures a great experience for your customers and greater sales opportunities for you.',
    title='Inventory Management',
    version='1.0.0',
    servers=[
        {'description': 'Production URL', 'url': 'https://marketplace.walmartapis.com'},
        {'description': 'Sandbox URL', 'url': 'https://sandbox.walmartapis.com'},
    ],
)


@app.post(
    '/v3/feeds',
    description=""" Updates inventory for items in bulk. 
Seller Can either use feed type "inventory" or "MP_INVENTORY" 
* Inventory spec 1.4 feed type: inventory 
* Inventory spec 1.5 feed type: MP_INVENTORY 

Please Note: Multi Node Inventory Update Feed (feedType=MP_INVENTORY) only supports JSON Request and Responses. Refer to "MultiNode_Bulk_Inventory_Update_Request.json" for the corresponding request sample 
 
Refer to the <a href="https://developer.walmart.com/doc/us/us-mp/us-mp-inventory/">guide section</a> for more detailed guide around each of the feed types 

 Refer to the throttling limits before uploading the Feed Files. """,
    tags=['inventory_management', 'bulk_item_updates'],
    security=[],
)
def update_bulk_inventory(
    feed_type: FeedType = Query(..., alias='feedType'),
    ship_node: Optional[str] = Query(None, alias='shipNode'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    file: UploadFile = ...,
):
    """
    Bulk Item Inventory Update
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v3/fulfillment/inventory',
    description=""" You can use this API to get the current Available to Sell inventory quantities for all WFS items in your catalog. You can also query specific SKUs or filter to only items updated after a specific date in order to reduce the response size. """,
    tags=['inventory_management', 'sku_retrieval_operations'],
    security=[],
)
def get_w_f_s_inventory(
    sku: Optional[str] = None,
    from_modified_date: Optional[str] = Query(None, alias='fromModifiedDate'),
    to_modified_date: Optional[str] = Query(None, alias='toModifiedDate'),
    limit: Optional[str] = '10',
    offset: Optional[str] = '0',
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
):
    """
    WFS Inventory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v3/inventories',
    description=""" This API will retrieve the inventory count for all of a seller's items across all ship nodes by item to ship node mapping. Inventory can be zero or non-zero. Please note that NextCursor value changes and it needs to be passed on from the previous call to next call. """,
    tags=['inventory_management', 'bulk_item_updates', 'sku_retrieval_operations'],
    security=[],
)
def get_multi_node_inventory_for_all_sku_and_all_ship_nodes(
    limit: Optional[str] = '10',
    next_cursor: Optional[str] = Query(None, alias='nextCursor'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
):
    """
    Multiple Item Inventory for All Ship Nodes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v3/inventories/{sku}',
    description=""" This API will retrieve the inventory count for an item across all ship nodes or one specific ship node. You can specify the ship node for which you want to fetch the inventory """,
    tags=['inventory_management', 'sku_retrieval_operations'],
    security=[],
)
def get_multi_node_inventory_for_sku_and_all_shipnodes(
    sku: str,
    ship_node: Optional[str] = Query(None, alias='shipNode'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
):
    """
    Single Item Inventory by Ship Node
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v3/inventories/{sku}',
    description=""" This API will update the inventory for an item across one or more fulfillment centers, known as ship nodes. """,
    tags=['inventory_management'],
    security=[],
)
def update_multi_node_inventory(
    sku: str,
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    body: V3InventoriesSkuPutRequest = ...,
):
    """
    Update Item Inventory per Ship Node
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v3/inventory',
    description=""" You can use this API to get the inventory for a given item. """,
    tags=['inventory_management', 'sku_retrieval_operations'],
    security=[],
)
def get_inventory(
    sku: str,
    ship_node: Optional[str] = Query(None, alias='shipNode'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
):
    """
    Inventory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v3/inventory',
    description=""" Updates the inventory for a given item. """,
    tags=['inventory_management'],
    security=[],
)
def update_inventory_for_an_item(
    sku: str,
    ship_node: Optional[str] = Query(None, alias='shipNode'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    body: V3InventoryPutRequest = ...,
):
    """
    Update inventory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
