# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:09:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Unit(Enum):
    EACH = 'EACH'


class AvailToSellQty(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Cause(BaseModel):
    code: Optional[str] = None
    description: Optional[str] = None
    field: Optional[str] = None
    type: Optional[str] = None


class AvailToSellQty1(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node(BaseModel):
    availToSellQty: Optional[AvailToSellQty1] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    inputQty: Optional[InputQty] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Inventory(BaseModel):
    nodes: Optional[List[Node]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Elements(BaseModel):
    inventories: Optional[List[Inventory]] = None


class Category(Enum):
    APPLICATION = 'APPLICATION'
    SYSTEM = 'SYSTEM'
    REQUEST = 'REQUEST'
    DATA = 'DATA'


class Severity(Enum):
    INFO = 'INFO'
    WARN = 'WARN'
    ERROR = 'ERROR'


class Error(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class FeedId(BaseModel):
    additionalAttributes: Optional[Dict[str, Any]] = None
    errors: Optional[Dict[str, Any]] = None
    feedId: Optional[str] = Field(
        None,
        description='A unique ID, returned from the Bulk Upload API, used for tracking the feed file',
    )


class AvailToSellQty2(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty1(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty1(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node1(BaseModel):
    availToSellQty: Optional[AvailToSellQty2] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    inputQty: Optional[InputQty1] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty1] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class GetAllInventoriesDTO(BaseModel):
    nodes: Optional[List[Node1]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class AvailToSellQty3(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty2(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty2(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class GetAllInventoriesNodeDTO(BaseModel):
    availToSellQty: Optional[AvailToSellQty3] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    inputQty: Optional[InputQty2] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty2] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Headers(BaseModel):
    limit: Optional[int] = Field(
        None, description='Information about the quantity in inventory'
    )
    offset: Optional[int] = Field(
        None,
        description='Offset is the number of records you wish to skip before selecting results.',
    )
    totalCount: Optional[int] = Field(
        None, description='Total number of results for query.'
    )


class InputQty3(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class AvailToSellQty4(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Error1(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class InputQty4(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty3(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node2(BaseModel):
    availToSellQty: Optional[AvailToSellQty4] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    errors: Optional[List[Error1]] = None
    inputQty: Optional[InputQty4] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty3] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class InventoriesDTO(BaseModel):
    nodes: Optional[List[Node2]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Quantity(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Inventory1(BaseModel):
    quantity: Quantity = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class ShipNode(BaseModel):
    availToSellQty: Optional[int] = Field(
        None,
        description='The available quantity is the quantity of an item that is available to be allocated to orders.',
    )
    modifiedDate: Optional[str] = Field(
        None, description='Last changes date for the item.'
    )
    onHandQty: Optional[int] = Field(
        None,
        description='The on-hand balance is the quantity of active inventory stored at the warehouse.Active inventory is defined as the usable amount of an item that is in the warehouse.Inventory is active if it is not damaged, expired or being inspected.',
    )
    shipNodeType: Optional[str] = Field(
        None,
        description="Identifies fulfillment aspect of invetory. Walmart, seller or 3PL fulfilled. Possible value is 'WFSFulfilled'. In later phase we will also add seller fulfilled inventory.",
    )


class InventoryWFS(BaseModel):
    shipNodes: Optional[List[ShipNode]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Meta(BaseModel):
    nextCursor: Optional[str] = Field(
        None, description='Used for pagination to fetch the next set of items.'
    )
    totalCount: Optional[float] = Field(
        None, description="Total number of Skus of the Seller. Example: '235'"
    )


class AvailToSellQty5(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty5(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty4(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node3(BaseModel):
    availToSellQty: Optional[AvailToSellQty5] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    inputQty: Optional[InputQty5] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty4] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Inventory2(BaseModel):
    nodes: Optional[List[Node3]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Elements1(BaseModel):
    inventories: Optional[List[Inventory2]] = None


class MultiNodeInventoryFetchResponseDTO(BaseModel):
    elements: Optional[Elements1] = None
    meta: Optional[Meta] = None


class InputQty6(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node4(BaseModel):
    inputQty: InputQty6 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: str = Field(
        ...,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Inventories(BaseModel):
    nodes: List[Node4]


class MultiNodeInventoryUpdateRequestDTO(BaseModel):
    inventories: Inventories


class Error2(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class Node5(BaseModel):
    errors: Optional[List[Error2]] = Field(
        None, description='Node Update Error description.'
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )
    status: Optional[str] = Field(
        None, description="Node Update status. Example: 'Success'"
    )


class MultiNodeInventoryUpdateResponseDTO(BaseModel):
    nodes: Optional[List[Node5]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class AvailToSellQty6(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Error3(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class InputQty7(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty5(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class NodeDTO(BaseModel):
    availToSellQty: Optional[AvailToSellQty6] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    errors: Optional[List[Error3]] = None
    inputQty: Optional[InputQty7] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty5] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class InventoryItem(BaseModel):
    shipNodes: Optional[List[ShipNode]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Payload(BaseModel):
    inventory: Optional[List[InventoryItem]] = None


class ReservedQty6(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ShipNodes(BaseModel):
    availToSellQty: Optional[int] = Field(
        None,
        description='The available quantity is the quantity of an item that is available to be allocated to orders.',
    )
    modifiedDate: Optional[str] = Field(
        None, description='Last changes date for the item.'
    )
    onHandQty: Optional[int] = Field(
        None,
        description='The on-hand balance is the quantity of active inventory stored at the warehouse.Active inventory is defined as the usable amount of an item that is in the warehouse.Inventory is active if it is not damaged, expired or being inspected.',
    )
    shipNodeType: Optional[str] = Field(
        None,
        description="Identifies fulfillment aspect of invetory. Walmart, seller or 3PL fulfilled. Possible value is 'WFSFulfilled'. In later phase we will also add seller fulfilled inventory.",
    )


class SupplyQuantity(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty8(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node6(BaseModel):
    inputQty: InputQty8 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: str = Field(
        ...,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class UpdateInventoriesRequestDTO(BaseModel):
    nodes: List[Node6]


class InputQty9(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class UpdateInventoriesRequestNodeDTO(BaseModel):
    inputQty: InputQty9 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: str = Field(
        ...,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Error4(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class UpdateInventoriesResponseNodeDTO(BaseModel):
    errors: Optional[List[Error4]] = Field(
        None, description='Node Update Error description.'
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )
    status: Optional[str] = Field(
        None, description="Node Update status. Example: 'Success'"
    )


class InventoryItem1(BaseModel):
    shipNodes: Optional[List[ShipNode]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Payload1(BaseModel):
    inventory: Optional[List[InventoryItem1]] = None


class WfsInventoryDTO(BaseModel):
    headers: Optional[Headers] = None
    payload: Optional[Payload1] = None


class FeedType(Enum):
    inventory = 'inventory'
    MP_INVENTORY = 'MP_INVENTORY'


class V3FeedsPostRequest(BaseModel):
    file: bytes = Field(..., description='Feed file to upload')


class V3FeedsPostResponse(BaseModel):
    additionalAttributes: Optional[Dict[str, Any]] = None
    errors: Optional[Dict[str, Any]] = None
    feedId: Optional[str] = Field(
        None,
        description='A unique ID, returned from the Bulk Upload API, used for tracking the feed file',
    )


class InventoryItem2(BaseModel):
    shipNodes: Optional[List[ShipNode]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Payload2(BaseModel):
    inventory: Optional[List[InventoryItem2]] = None


class V3FulfillmentInventoryGetResponse(BaseModel):
    headers: Optional[Headers] = None
    payload: Optional[Payload2] = None


class AvailToSellQty7(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class InputQty10(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty7(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node7(BaseModel):
    availToSellQty: Optional[AvailToSellQty7] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    inputQty: Optional[InputQty10] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty7] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Inventory3(BaseModel):
    nodes: Optional[List[Node7]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Elements2(BaseModel):
    inventories: Optional[List[Inventory3]] = None


class V3InventoriesGetResponse(BaseModel):
    elements: Optional[Elements2] = None
    meta: Optional[Meta] = None


class AvailToSellQty8(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Error5(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class InputQty11(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class ReservedQty8(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node8(BaseModel):
    availToSellQty: Optional[AvailToSellQty8] = Field(
        None,
        description='Quantity of an item that is available to be allocated to orders',
    )
    errors: Optional[List[Error5]] = None
    inputQty: Optional[InputQty11] = Field(
        None, description='Quantity of an item that is input by the seller'
    )
    reservedQty: Optional[ReservedQty8] = Field(
        None,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class V3InventoriesSkuGetResponse(BaseModel):
    nodes: Optional[List[Node8]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class InputQty12(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class Node9(BaseModel):
    inputQty: InputQty12 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    shipNode: str = Field(
        ...,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )


class Inventories1(BaseModel):
    nodes: List[Node9]


class V3InventoriesSkuPutRequest(BaseModel):
    inventories: Inventories1


class Error6(BaseModel):
    category: Optional[Category] = None
    causes: Optional[List[Cause]] = None
    code: str
    description: Optional[str] = None
    errorIdentifiers: Optional[Dict[str, Dict[str, Any]]] = None
    field: Optional[str] = None
    info: Optional[str] = None
    severity: Optional[Severity] = None


class Node10(BaseModel):
    errors: Optional[List[Error6]] = Field(
        None, description='Node Update Error description.'
    )
    shipNode: Optional[str] = Field(
        None,
        description='ShipNode Id of the ship node for which the inventory is requested',
    )
    status: Optional[str] = Field(
        None, description="Node Update status. Example: 'Success'"
    )


class V3InventoriesSkuPutResponse(BaseModel):
    nodes: Optional[List[Node10]] = None
    sku: Optional[str] = Field(
        None,
        description='An arbitrary alphanumeric unique ID, specified by the seller, which identifies each item.',
    )


class Quantity1(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryGetResponse(BaseModel):
    quantity: Quantity1 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class Quantity2(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryGetResponse1(BaseModel):
    quantity: Quantity2 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class Quantity3(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryPutRequest(BaseModel):
    quantity: Quantity3 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class Quantity4(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryPutRequest1(BaseModel):
    quantity: Quantity4 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class Quantity5(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryPutResponse(BaseModel):
    quantity: Quantity5 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )


class Quantity6(BaseModel):
    amount: float = Field(..., description='Inventory Count')
    unit: Unit = Field(..., description="The unit of measurement. Example: 'EACH'")


class V3InventoryPutResponse1(BaseModel):
    quantity: Quantity6 = Field(
        ...,
        description='Quantity that has been ordered by the customers but not yet shipped',
    )
    sku: str = Field(
        ...,
        description='A seller-provided Product ID. Response will have decoded value.',
    )
